### ISSUE TITLE
pid variable should be `processId`

### ISSUE THREAD

**Issue by berendsliedrecht** [animo/expo-ausweis-sdk#1]
I think most comments will be quite nit picks, but since this sdk will have some connection to the PID, I think it would be good to rename the var to `processId` to avoid confusion.

https://github.com/animo/expo-ausweis-sdk/blob/b249c5c26d8b8f46d48877c8f68c3598f5a7c007/android/src/main/java/id/animo/ausweissdk/AusweisSdkUtils.kt#L17

**Comment by TimoGlastra** [comment]
Yeah I saw it as well, but more thought of it as funny. 

I just now looked at the docs again, and the new version they released yesterday actually simplified this code a lot: https://www.ausweisapp.bund.de/sdk/android.html#initialization-of-the-android-application. So i'll update it 👍
