### ISSUE TITLE
Group variable can be reused

### ISSUE THREAD

**Issue by berendsliedrecht** [animo/expo-ausweis-sdk#2]
https://github.com/animo/expo-ausweis-sdk/blob/b249c5c26d8b8f46d48877c8f68c3598f5a7c007/android/build.gradle#L35

**Comment by TimoGlastra** [comment]
How would that syntax work? Just placing group there as variable gives build errors.

**Comment by TimoGlastra** [comment]
Need to use `def group =` so can't use the group. Not worth it IMO. as def means it won't configure the build.gralde. So we need two variables

<img width="575" alt="image" src="https://github.com/animo/expo-ausweis-sdk/assets/23165168/988a9a8a-3717-407c-b5a2-9f6b8e1de3e3">
