### ISSUE TITLE
Are these flags provided by some documentation?

### ISSUE THREAD

**Issue by berendsliedrecht** [animo/expo-ausweis-sdk#3]
https://github.com/animo/expo-ausweis-sdk/blob/b249c5c26d8b8f46d48877c8f68c3598f5a7c007/android/src/main/java/id/animo/ausweissdk/AusweisSdkConnectionHandler.kt#L126

**Comment by TimoGlastra** [comment]
YES, I'll add some comments. But everything comes from https://www.ausweisapp.bund.de/sdk/android.html#initialization-of-the-android-application
