### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by berendsliedrecht** [animo/expo-ausweis-sdk#4]
Does the SDK sendCommand have a command to retrieve the latest error? Might be good to call that here and if that fails return the generic error.

https://github.com/animo/expo-ausweis-sdk/blob/b249c5c26d8b8f46d48877c8f68c3598f5a7c007/android/src/main/java/id/animo/ausweissdk/AusweisSdkConnectionHandler.kt#L110

**Comment by TimoGlastra** [comment]
Not really. There's messages events that are emitted if a command execution fails for a reason. But if the sending of the command failed, we only have the success value.

**Comment by TimoGlastra** [comment]
If you can find something in the docs, I'm happy to look into it, but can't find anything: https://www.ausweisapp.bund.de/sdk/index.html
