### ISSUE TITLE
Does this method need to be async?

### ISSUE THREAD

**Issue by berendsliedrecht** [animo/expo-ausweis-sdk#5]
https://github.com/animo/expo-ausweis-sdk/blob/b249c5c26d8b8f46d48877c8f68c3598f5a7c007/android/src/main/java/id/animo/ausweissdk/AusweisSdkModule.kt#L31

**Comment by berendsliedrecht** [comment]
Ah, its because of iOS right?

**Comment by TimoGlastra** [comment]
We need to coroutine, `connectionHandler.bindService(context)` is async (it's a suspend function, and thus the function will wait until that method resolves, with a timeout 10 seconds). You don't need an `await ` for that in a kotlin coroutine context
