### ISSUE TITLE
Won't we have issues with the licenses?

### ISSUE THREAD

**Issue by berendsliedrecht** [animo/expo-ausweis-sdk#6]
Forgot the exact details of the discussion, but this library uses a EUPL, right? Can we just convert our project to Apache 2.0?

https://github.com/animo/expo-ausweis-sdk/blob/b249c5c26d8b8f46d48877c8f68c3598f5a7c007/Specs/AusweisApp2/2.1.1/AusweisApp2.podspec#L6

**Comment by berendsliedrecht** [comment]
Also, what is the reason for the double podspec? One for our wrapper and one for their xc framework?

**Comment by TimoGlastra** [comment]
License discussion is ongoing, so I should probably remove it for now.

**Comment by TimoGlastra** [comment]
Re pods, yes one is for our wrapper, the other for their XC Framework. It needs to be a podsource `source https://github.com/animo/expo-ausweis-sdk`. That way it will fetch the podspec, and then it will look at source to fetch the xcframework from governikus repo. If you use a local podspec, it won't fetch the remote source :( And I can't combine them into one pod as they have different source locations.

This is the same way we did it with Indy SDK binary.
