### ISSUE TITLE
Different parameter type

### ISSUE THREAD

**Issue by berendsliedrecht** [animo/expo-ausweis-sdk#7]
Can't the function parameter have a different type? I think it would be good to just accept a swift String and convert it into an unsafe CChar pointer locally. Makes the function safe and it is the functions responsibility to make sure the CChar is safe (which it is due to converting it from a swift string) instead of the caller.

https://github.com/animo/expo-ausweis-sdk/blob/b249c5c26d8b8f46d48877c8f68c3598f5a7c007/ios/AusweisSdkModule.swift#L8

**Comment by TimoGlastra** [comment]
This callback is passed to the Ausweis SDK. So we don't control the input of this callback. I convert it to string here: https://github.com/animo/expo-ausweis-sdk/blob/b249c5c26d8b8f46d48877c8f68c3598f5a7c007/ios/AusweisSdkModule.swift#L10
