### ISSUE TITLE
Incorrect License for AA2 in podspec?

### ISSUE THREAD

**Issue by MichaelSchmidtME** [animo/expo-ausweis-sdk#8]
Assuming that the license info in the podspec shall specify the license of the referenced 3rd party, this seems to be incorrect (should be EUPL 1.2):
https://github.com/animo/expo-ausweis-sdk/blob/b249c5c26d8b8f46d48877c8f68c3598f5a7c007/Specs/AusweisApp2/2.1.1/AusweisApp2.podspec#L6

**Comment by TimoGlastra** [comment]
We will change it, thanks!
